<?php $this->partial("shared/header"); ?>

<body class="adminbody">

<div id="main">

	<!-- top bar navigation -->
	<?php $this->partial('shared/navigation'); ?>
	<!-- End Navigation -->
	
 
	<!-- Left Sidebar -->
	<?php $this->partial('shared/left-sidebar'); ?>
	<!-- End Sidebar -->


    <div class="content-page">
	
		<!-- Start content -->
        <div class="content">
            
			<div class="container-fluid">
					
				<div class="row">
					<div class="col-xl-12">
						<div class="breadcrumb-holder">
    						<h1 class="main-title float-left"><?php echo $breadcrum;?></h1>
    						<ol class="breadcrumb float-right">
    							<li class="breadcrumb-item">Home</li>
    							<li class="breadcrumb-item active"><?php echo $breadcrum;?></li>
    						</ol>
    						<div class="clearfix"></div>
						</div>
					</div>
				</div>
				<!-- end row -->
                <?php echo $this->getContent(); ?>
            </div>
			<!-- END container-fluid -->

		</div>
		<!-- END content -->

    </div>
	<!-- END content-page -->
    
    <?php $this->partial('shared/footer'); ?>
</div>
<!-- END main -->

<script src="<?php echo BASE_URL ?>/assets/js/modernizr.min.js"></script>
<script src="<?php echo BASE_URL ?>/assets/js/jquery.min.js"></script>
<script src="<?php echo BASE_URL ?>/assets/js/moment.min.js"></script>
		
<script src="<?php echo BASE_URL ?>/assets/js/popper.min.js"></script>
<script src="<?php echo BASE_URL ?>/assets/js/bootstrap.min.js"></script>

<script src="<?php echo BASE_URL ?>/assets/js/detect.js"></script>
<script src="<?php echo BASE_URL ?>/assets/js/fastclick.js"></script>
<script src="<?php echo BASE_URL ?>/assets/js/jquery.blockUI.js"></script>
<script src="<?php echo BASE_URL ?>/assets/js/jquery.nicescroll.js"></script>

<!-- App js -->
<script src="<?php echo BASE_URL ?>/assets/js/pikeadmin.js"></script>

<!-- BEGIN Java Script for this page -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

	<!-- Counter-Up-->
	<script src="<?php echo BASE_URL ?>/assets/plugins/waypoints/lib/jquery.waypoints.min.js"></script>
	<script src="<?php echo BASE_URL ?>/assets/plugins/counterup/jquery.counterup.min.js"></script>
	<script>
		$(document).ready(function() {
			$('#web-config').DataTable();
		} );
	</script>

</body>
</html>