<div class="left main-sidebar">
	
    <div class="sidebar-inner leftscroll">

    	<div id="sidebar-menu">

    	<ul>

    		<li class="submenu">
    			<a class="active" href="#"><i class="fa fa-fw fa-bars"></i><span> Dashboard </span> </a>
            </li>
    		
    		<li class="submenu">
                <a href="#"><i class="fa fa-fw fa-table"></i> <span> Web Config </span> <span class="menu-arrow"></span></a>
				<ul class="list-unstyled">
					<li><a href="<?php echo $this->url->get('admin/webconfig/index'); ?>">Configs</a></li>
					<li><a href="<?php echo $this->url->get('admin/webconfig/add'); ?>">Add</a></li>
				</ul>
            </li>
    							
            <li class="submenu">
                <a href="#"><i class="fa fa-fw fa-tv"></i> <span> Proxy Config</span> <span class="menu-arrow"></span></a>
                <ul class="list-unstyled">
                    <li><a href="<?php echo $this->url->get('admin/proxy/index'); ?>">Proxies</a></li>
                    <li><a href="<?php echo $this->url->get('admin/proxy/add'); ?>">Add</a></li>
                </ul>
            </li>

    		<li class="submenu">
                <a href="#"><i class="fa fa-fw fa-file-text-o"></i> <span> Dictionary </span> <span class="menu-arrow"></span></a>
                <ul class="list-unstyled">
                    <li><a href="forms-general.html">Biagrams</a></li>
					<li><a href="forms-select2.html">Trigrams</a></li>
                </ul>
            </li>     
    			
        </ul>

        <div class="clearfix"></div>

    	</div>

    	<div class="clearfix"></div>

    </div>

</div>